// Users
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const LOAD_USER_INFO = 'LOAD_USER_INFO';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const UPDATE_ZHIMA = 'UPDATE_ZHIMA';
export const NOTHING = 'NOTHING';
export const GEO_LOCATION = 'GEO_LOCATION';
export const UPDATE_YHK = 'UPDATE_YHK';
export const UPDATE_JXL = 'UPDATE_JXL';

export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_ERR_MODAL = 'CLOSE_ERR_MODAL';
export const SHOW_ERR_MODAL = 'SHOW_ERR_MODAL';
export const UPDATE_NAV = 'UPDATE_NAV';
export const GO_BACK = 'GO_BACK';

// loan2
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const CREATE_LOAN_START = 'CREATE_LOAN_START';
export const CREATE_LOAN_FULFILLED = 'CREATE_LOAN_FULFILLED';
export const CREATE_LOAN_REJECTED = 'CREATE_LOAN_REJECTED';
export const GET_LOAN_START = 'GET_LOAN_START';
export const GET_LOAN_FULFILLED = 'GET_LOAN_FULFILLED';
export const GET_LOAN_REJECTED = 'GET_LOAN_REJECTED';
export const GET_LOANLIST_START = 'GET_LOANLIST_START';
export const GET_LOANLIST_FULFILLED = 'GET_LOANLIST_FULFILLED';
export const GET_LOANLIST_REJECTED = 'GET_LOANLIST_REJECTED';
export const CANCEL_LOAN_START = 'CANCEL_LOAN_START';
export const CANCEL_LOAN_FULFILLED = 'CANCEL_LOAN_FULFILLED';
export const CANCEL_LOAN_REJECTED = 'CANCEL_LOAN_REJECTED';
export const SUBMIT_LOAN_START = 'SUBMIT_LOAN_START';
export const SUBMIT_LOAN_FULFILLED = 'SUBMIT_LOAN_FULFILLED';
export const SUBMIT_LOAN_REJECTED = 'SUBMIT_LOAN_REJECTED';
export const GET_CONTRACTINFO_START = 'GET_CONTRACTINFO_START';
export const GET_CONTRACTINFO_FULFILLED = 'GET_CONTRACTINFO_FULFILLED';
export const GET_CONTRACTINFO_REJECTED = 'GET_CONTRACTINFO_REJECTED';

export const GET_MINE_PRODUCTS = 'GET_MINE_PRODUCTS';

// userInfo
export const CREATE_USERINFO = 'CREATE_USERINFO';
export const JXL_APPLY = 'JXL_APPLY';
export const JXL_MOBILE = 'JXL_MOBILE';
export const JXL_JINGDONG = 'JXL_JINGDONG';
export const JXL_NOTE = 'JXL_NOTE';
export const RETRYNOTE = 'RETRYNOTE';
export const USERINFO_SKIP = 'USERINFO_SKIP';
export const GET_USERINFO = 'GET_USERINFO';

// userinfo hl
export const CREATE_USERINFO_HL = 'CREATE_USERINFO_HL';
export const HL_APPLY = 'HL_APPLY';
export const HL_MOBILE = 'HL_MOBILE';
export const HL_NOTE = 'HL_NOTE';
export const USERINFO_SKIP_HL = 'USERINFO_SKIP_HL';
export const RETRYNOTE_HL = 'RETRYNOTE_HL';
export const HL_JINGDONG = 'HL_JINGDONG';

// repay
export const REPAY = 'REPAY';
export const RENEWAL = 'RENEWAL';
export const INIT_REPAYMENT = 'INIT_REPAYMENT';
export const INIT_CARDBIND = 'INIT_CARDBIND';
export const CARDBIND = 'CARDBIND';
export const CARDBIND_CONFIRM = 'CARDBIND_CONFIRM';
export const CARDBIND_REPAY = 'CARDBIND_REPAY';
export const REPAY_SUCCESS = 'REPAY_SUCCESS';
export const INPUT_CHANGE = 'INPUT_CHANGE';
export const SWITCH_BUTTON = 'SWITCH_BUTTON';
export const SHOW_CLOSE_PAY_MODAL = 'SHOW_CLOSE_PAY_MODAL';

// user-profile
export const DEFAULT = 'DEFAULT';
export const SELECT_USERPROFILE_USERID = 'SELECT_USERPROFILE_USERID';
export const USER_AVATAR = 'USER_AVATAR';

// cmy credit
export const MY_CREDIT_ZHIMA = 'MY_CREDIT_ZHIMA';
export const MY_CREDIT_JXL = 'MY_CREDIT_JXL';
export const MY_CREDIT_BANKCARD = 'MY_CREDIT_BANKCARD';
export const MY_CREDIT_PIC_UPLOAD = 'MY_CREDIT_PIC_UPLOAD';
export const MY_CREDIT_INIT = 'MY_CREDIT_INIT';
export const LLDATTESTATIONTYPE = 'LLDATTESTATIONTYPE';

// cpicUpload
export const UPLOAD_IMAGE1 = 'UPLOAD_IMAGE1';
export const UPLOAD_IMAGE2 = 'UPLOAD_IMAGE2';
export const UPLOAD_IMAGE3 = 'UPLOAD_IMAGE3';
export const UPDATE_IDINFO = 'UPDATE_IDINFO';

export const REG_SOURCE = 'REG_SOURCE';

export const ROUTE_TO_NEXT = 'ROUTE_TO_NEXT';

export const LOADING = 'LOADING';
